@host = localhost:3500


POST http://{{host}}/v1/security/signup
content-type: application/json

{
    "Email":"juan.navarro68@gmail.com",
    "FamilyName": "Navarro",
    "GivenName":"Juan",
    "ImageURL":"https://lh3.googleusercontent.com/a/AEdFTp6fK7kniHV6u_TKMiqMy1blxuVJetbTPfdA5ASuqA=s96-c",
    "Name":"Juan Navarro",
     "GoogleID":"111751505227207835600",
    "CategoryID":"4234c285-5bab-49bf-a5d7-c34ff27ee256",
    "PermissionID":"ffb9b6a3-5c49-4b0f-90a4-2338b93154b9"
}

###
POST http://{{host}}ç
content-type: application/json

{
    "Email":"juan.navarro68@gmail.com",
    "Password":"",
    "GoogleID":"111751505227207835600"
}
###
POST http://{{host}}/v1/security/login
content-type: application/json

{
    "Email":"juan.navarro3@gmail.com",
    "Password":"jjna100268",
}
###
GET http://{{host}}/v1/security/validate
### Users
GET http://{{host}}/v1/catalogs/users
?page=1&limit=50
content-type: application/json
###

POST http://{{host}}/v1/catalogs/permissions
Content-Type: application/json

{
    "Description": "Responsable"
}
###
POST http://{{host}}/v1/catalogs/dojos
Content-Type: application/json

{
    "Name":        "El Fortin",
    "Description": "Sei Shin Kan El Fortin",
    "ShortName":   "El Fortin",
    "Address":     "Guarda Nacional a un lado de la tienda de Gera",
    "Phone":       "(33) 3125-5899",
    "ManagerID":   "a401d49b-2961-4415-841f-5e38bd546f09",
    "Active":      true
}
###
GET  http://{{host}}/v1/catalogs/dojos
Content-Type: application/json
###

POST http://{{host}}/v1/catalogs/category
Content-Type: application/json

{
    "Description": "Negro",
    "Color1": "#000000",
    "Color2": "#000000",
    "level": "11",
    "Active": "true"
}
###

GET http://{{host}}/v1/catalogs/category
Content-Type: application/json

###

GET  http://{{host}}/v1/catalogs/schedule
Content-Type: application/json
###
